site_name: MkDocs - Resize images plugin
site_url: https://resize.kubaandrysek.cz/
site_author: Jakub Andrýsek
site_description: >-
  MkDocs plugin to resize images according to the configuration.

# Repository
repo_name: JakubAndrysek/mkdocs-resize-images
repo_url: https://github.com/JakubAndrysek/mkdocs-resize-images
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright © 2023 Jakub Andrýsek

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github


  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
#    property: G-FC199H98G7
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!


use_directory_urls: True

plugins:
  - search
  - open-in-new-tab
  - glightbox
  - social
  - resize-images:
     source-dir: assets-large
     target-dir: assets
     size: [800, 600]
     enable_cache: True


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: 'README.md'
  - Example: 'example.md'
