name: Build and deploy docs to GitHub Pages
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: python -m pip install -e .\[dev\]
      - run: make fixRelativeLinkDocs

      - name: Remove 'assets-large' from .gitignore
        run: sed -i '/assets-large/d' .gitignore

      - run: mkdocs gh-deploy --force